idf_component_register(
    SRCS 
        main.cpp
        app.cpp
        ProductService.cpp
        ProductsManager.cpp
        RecipeGoodFoodService.cpp
        RecipeGialloZafferanoService.cpp
        RecipeSuggestionsManager.cpp
        RecipeDetailService.cpp
        FavouriteService.cpp
        FavouritesManager.cpp
        WifiManager.cpp
        ui_extensions.cpp
        ui_extensions_products.cpp
        ui_extensions_recipes.cpp
        ui_extensions_recipe_detail.cpp
        ui_extensions_favourites.cpp
        filters_ui.cpp
        ui/screens.c
        ui/styles.c
        ui/images.c
        ui/actions.cpp
        ui/ui.c
        ui/ui_image_shopping.c
        ui/ui_image_chef.c
        ui/ui_image_restaurant.c
        ui/ui_font_ext_font_montserrat_18.c
        ui/ui_image_snowflake.c
    INCLUDE_DIRS 
    . 
    ui)

idf_component_get_property(LVGL_LIB lvgl__lvgl COMPONENT_LIB)
target_compile_options(
    ${LVGL_LIB} 
    PRIVATE
        -DLV_LVGL_H_INCLUDE_SIMPLE
)